### ISSUE TITLE
grade level button css

### ISSUE THREAD

**Issue by GUIMess** [bob-fornal/how-to-take-a-test#10]
simple selector issue for the grade-level buttons. Cannot get selectors to work on my machine. 

button.grade-level-button SHOULD work, but hasn't for me.

![image](https://user-images.githubusercontent.com/1313712/224412894-c4c657eb-9116-424d-a2d6-c8479a5fd267.png)

**Comment by bob-fornal** [comment]
Looking at the code now.

**Comment by bob-fornal** [comment]
Added the code to your branch. The CSS was perfect. The function to set `this.selected` was right, as well. It wasn't called.
![Screen Shot 2023-03-10 at 14 54 15](https://user-images.githubusercontent.com/6015580/224415180-954bb463-5b1a-4ce8-893a-499fe47f0833.png)

**Comment by GUIMess** [comment]
I literally just typed that in and it magically works. Couldn't figure out why. Thanks for the explanation. And thanks Dillon for helping too!
