### ISSUE TITLE
NG: 304 for grade-level-selection on HTTAT-6

### ISSUE THREAD

**Issue by GUIMess** [bob-fornal/how-to-take-a-test#11]
![image](https://user-images.githubusercontent.com/1313712/224433233-bf2c4cc5-9ed7-4572-aead-3555314b0bed.png)

**Comment by bob-fornal** [comment]
If this is in a unit test run, import and add the component to the home component.

**Comment by GUIMess** [comment]
It was and that of course fixed it.
