### ISSUE TITLE
linter may not be installed correctly

### ISSUE THREAD

**Issue by GUIMess** [bob-fornal/how-to-take-a-test#22]
or in the wrong place. When I run `ng lint` I get 
![image](https://user-images.githubusercontent.com/1313712/224584652-939aa6f8-57d5-45e2-aaaf-7a9f100a1ff3.png)

https://github.com/bob-fornal/how-to-take-a-test/tree/HTTAT-20-add-eslint-with-rules

**Comment by bob-fornal** [comment]
Try this `npm install --save-dev eslint-config-prettier` ... from **[HERE](https://stackoverflow.com/q/70126114)**

**Comment by bob-fornal** [comment]
Worked out the core issues.
